name: Deploy project docs

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:

jobs:
  deploy-docs-to-community:
    runs-on: ubuntu-latest
    env:
      NOP_SITE_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
    steps:
      - name: Create temp dirs
        run: mkdir project-docs nop-site
      - name: Copy SSH key
        run: mkdir ~/.ssh && echo $NOP_SITE_PRIVATE_KEY > ~/.ssh/id_rsa_nop
      - name: Check out site files
        run: |
          cd nop-site
          git init
          git remote add origin git@gitee.com:nop-platform/nop-platform.git
          git fetch
          git checkout master
          ls -al
          cd ..
          ls -al
      - uses: actions/checkout@v3
        with:
          path: project-docs
